### PR TITLE
feat: Adding folder and tag_prefix to module resource

### PR DESCRIPTION
**Pull request by BenjaminDecreusefond**
Hey @alfespa17 ! 

Do you think it would work ? From my understanding we only need to add parameters to the payload body of the post/update request for the module so that it can creates with the values. Did I miss something ?

### CODE REVIEW

**Comment by alfespa17** [comment]
I think it looks good

**Comment by alfespa17** [comment]
The build failed I think it is related to the go version change that you added, can you rollback that part @BenjaminDecreusefond ?

**Comment by alfespa17** [comment]
Once you fix the build issue I can merge the change

**Comment by BenjaminDecreusefond** [comment]
Okay, will do thanks !

**Comment by BenjaminDecreusefond** [comment]
@alfespa17 done it ! :)

**Comment by BenjaminDecreusefond** [comment]
@alfespa17 my bad I forget a little whitespace, just added it ! :)

**Comment by alfespa17** [comment]
It is failing @BenjaminDecreusefond

**Comment by BenjaminDecreusefond** [comment]
Very sorry, I ran gofmt it should be good now @alfespa17 !

**Comment by BenjaminDecreusefond** [comment]
@alfespa17 CI passed ! :)

**Pull request merged**
