### PR TITLE
feat: #48 Add support of tags

### LINKED ISSUE #48: Add support of tags to workspace configuration
Can we please add support of tags to workspace configuration? Thanks.

### PR DESCRIPTION
**Pull request by stanleyz**
Added two resources:

* `terrakube_tag` for organization level tags
* `terrakube_workspace_tag` for workspace level tags

Additional changes:

1. Add `.vscode` to `.gitignore`

fixes #48

### CODE REVIEW

**Comment by alfespa17** [comment]
> On another think, feels like `terrakube_organization_tag` is more suitable than `terrakube_tag`, what do you think? @alfespa17 should I change?

Yes I think it is better if you change it to `terrakube_organization_tag`

**Comment by stanleyz** [comment]
@alfespa17 please take another look. 

On a side topic, do you think we should add `go.sum` and `go.mod` to `.gitignore`? Or is it the one Dependabot requires to maintain the vulnerability database?

**Comment by alfespa17** [comment]
I understand that is not a good practice to add the go.sum or go.mod to the .gitignore file

**Comment by alfespa17** [comment]
I was testing creating `terrakube_organization_tag` and later update the tag name but it is not working

**Comment by stanleyz** [comment]
> I was testing creating `terrakube_organization_tag` and later update the tag name but it is not working

This should have been fixed now, please check. some weird copying and replacing happened before. Similarly fixed a typo/bug in the `workspace_vcs` resource.

**Comment by stanleyz** [comment]
> I understand that is not a good practice to add the go.sum or go.mod to the .gitignore file

yeah, I read so as well, but it's annoying that go asks `mod tidy` to update sum and mod every time and yet want them tracked in repos.

**Comment by alfespa17** [comment]
> > I was testing creating `terrakube_organization_tag` and later update the tag name but it is not working
> 
> This should have been fixed now, please check. some weird copying and replacing happened before. Similarly fixed a typo/bug in the `workspace_vcs` resource.

Thank you, now it is working

**Review by alfespa17 — APPROVED** [review]

**Pull request merged**
